backend/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

backend/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('profile/', views.profile, name='profile'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

backend/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from shop import settings

schema_view = get_schema_view(
    openapi.Info(title="Blog API",
        default_version="v1",
        description="A sample of Shop API for learning DRF",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="hello@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('store.urls')),
    path('api/', include('store.api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from . import views



app_name = 'store'

router = SimpleRouter()
router.register('users', views.UserViewSet, basename = 'users')



urlpatterns = [
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/<slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/product/<slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('categories/product/<str:pk>/add_rating/', views.api_add_rating, name='api_add_rating'),
    path('categories/product/<str:pk>/like/', views.api_addlike, name='api_add_like'),
    path('categories/product/<str:pk>/dislike/', views.api_add_dislike, name='api_add_dislike'),
    path('categories/product/<str:pk>/add_comment/', views.api_add_comment, name='api_add_comment'),
    path('api_profile/', views.api_profile, name='api_profile'),
    path('api_profile_orders/', views.api_profile_orders, name='api_profile_orders'),
    path('api_profile_update/', views.api_profile_update, name='api_profile_update'),
    path('cart/checkout/', views.api_order_create, name='api_order_create'),
    path('cart/api_get_token/', views.api_get_token, name='api_get_token'),
    path('cart/api_payment_process/', views.api_payment_process, name='api_payment_process'),
    path('login/', views.issue_token, name='issue_token'),
]

urlpatterns += router.urls

backend/store/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import *

app_name = 'store'
urlpatterns = [
	path('', index, name='index'),
	path('categories/', ShowCategories.as_view(), name='categories'),
	path('categories/<slug:category_slug>/', ShowCategory.as_view(), name='category'),
	path('products/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
	path('shops/', show_shops, name='shops'),
	path('about/', about_us, name='about'),
	path('register/', RegisterUser.as_view(), name='register'),
	path('login/', LoginUser.as_view(), name="login"),
	path('logout/', LogoutView.as_view(), name="logout"),
	path('ajax_receiver/', ajax_receiver, name='ajax_receiver'),
	path('products/<int:pk>/like/', addlike, name='add_like'),
	path('products/<int:pk>/dislike/', AddDislike.as_view(), name='add_dislike'),
]

backend/store/forms.py
from django import forms

from .models import Comment



class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active','author','likes','dislikes')
        widgets = {'product': forms.HiddenInput}

backend/store/api/views.py
from rest_framework import generics, status, permissions, viewsets

from ..models import Category, Product, Comment, Rating
from .serializers import CategorySerializer, ProductSerializer, CategoryListSerializer, RatingSerializer, OrderSerializer, OrderItemSerializer, OrderIDSerializer, ProfileSerializer, OrderItemModelSerializer, OrderItemProfileSerializer, CommentSerializer, UserSerializer, IssueTokenRequestSerializer, TokenSerializer
from django.contrib.auth import get_user_model
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated, AllowAny, IsAuthenticatedOrReadOnly
from rest_framework.authtoken.models import Token
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.contrib.auth import authenticate
from django.conf import settings

from orders.models import OrderItem, Order, Profile

import braintree


class CategoryListView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategoryListSerializer


class CategoryDetailView(generics.RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    lookup_field = 'slug'


class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'slug'


class UserViewSet(viewsets.ModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


@api_view(['POST'])
@permission_classes([AllowAny])
def issue_token(request):
    serializer = IssueTokenRequestSerializer(data=request.data)
    if serializer.is_valid():
        authenticated_user = authenticate(**serializer.validated_data)
        try:
            token = Token.objects.get(user=authenticated_user)
        except Token.DoesNotExist:
            token = Token.objects.create(user=authenticated_user)
        return Response(TokenSerializer(token).data)
    else:
        return Response(serializer.errors, status=400)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_addlike(request, pk, *args, **kwargs):

    if request.method == 'POST':
        post = Comment.objects.get(pk=pk)
        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)

        return JsonResponse({"success": True}, status=200)
    else:
        return JsonResponse({"success": False}, status=400)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_add_dislike(request, pk, *args, **kwargs):

    if request.method == 'POST':
        post = Comment.objects.get(pk=pk)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)
        
        return JsonResponse({"success": True}, status=200)
    else:
        return JsonResponse({"success": False}, status=400)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_add_rating(request, pk):
    if request.method == 'POST':
        serializer = RatingSerializer(data=request.data)
        if serializer.is_valid():
            try:
                rating = Rating.objects.get(product=serializer.data['product'], user=request.user)
                rating.stars = serializer.data['stars']
                rating.save()
            except Rating.DoesNotExist:
                product = get_object_or_404(Product, id=serializer.data['product'])
                rating = Rating.objects.create(user=request.user, product=product)
                rating.stars = serializer.data['stars']
                rating.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_add_comment(request, pk):
    if request.method == 'POST':
        serializer = CommentSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(author=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    else:
        comments = Comment.objects.filter(is_active=True, id=pk)
        serializer = CommentSerializer(comments, many=True)
        return Response(serializer.data)


@api_view(['POST'])
@permission_classes([AllowAny])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_order_create(request):
    if request.method == 'POST':
        serializer = OrderSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save
        order = Order.objects.create(first_name=serializer.data['first_name'],
                             last_name=serializer.data['last_name'],
                             email=serializer.data['email'],
                             address=serializer.data['address'],
                             postal_code=serializer.data['postal_code'],
                             city=serializer.data['city'],
                             )
        if request.user.is_authenticated:
            order.user = request.user
        order.save()
        serializer2 = OrderItemSerializer(data=request.data['cartItems'], many=True)
        if serializer2.is_valid():
                serializer2.save
        for i in range(len(serializer2.data)):
            product = get_object_or_404(Product, pk=serializer2.data[i]['id'])        
            OrderItem.objects.create(order=order,
                                        product=product,
                                        price=serializer2.data[i]['price'],
                                        quantity=serializer2.data[i]['quantity'])
        
        order_id_serializer = OrderSerializer(order)
        return Response(order_id_serializer.data)



gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)

@api_view(['GET'])
@permission_classes([AllowAny])
def api_get_token(request):
    client_token = gateway.client_token.generate()
    return Response(client_token)
    


@api_view(['POST'])
@permission_classes([AllowAny])
def api_payment_process(request):
               
    if request.method == 'POST':

        serializer = OrderIDSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save
        order = get_object_or_404(Order, id=serializer.data['orderid'])
        total_cost = order.get_total_cost()
                
        # retrieve nonce
        nonce = request.data.get('paymentMethodNonce', None)
        # create and submit transaction
        result = gateway.transaction.sale({
            'amount': f'{total_cost:.2f}',
            'payment_method_nonce': nonce,
            'options': {
                'submit_for_settlement': True
            }
        })

        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store the unique transaction id
            order.braintree_id = result.transaction.id
            order.save()
            return Response('Payment done')
        else:
            return Response('Payment canceled')
    

@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_profile(request):
    queryset = Profile.objects.get(user=request.user)
    serializer = ProfileSerializer(queryset)
    return Response(serializer.data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_profile_orders(request):
    orders = Order.objects.filter(user=request.user)
    serializer = OrderItemProfileSerializer(orders, many=True, context={'request': request})
    return Response(serializer.data)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication, TokenAuthentication])
def api_profile_update(request):
    if request.method == 'POST':
        serializer = ProfileSerializer(data=request.data)
        if serializer.is_valid():
            profile = Profile.objects.get(user=request.user)
            profile.first_name=serializer.data['first_name']
            profile.last_name=serializer.data['last_name']
            profile.email=serializer.data['email']
            profile.address=serializer.data['address']
            profile.postal_code=serializer.data['postal_code']
            profile.city=serializer.data['city']
            profile.save()
        return Response('Профиль успешно обновлен')

        



        

backend/store/templates/store/about.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>О Нас</h1>
{% endblock page_header %}


{% block content %}
<div class="w-100"><hr></div>
<h6>Работаем с 1995ого года, поставляем комплектующие по оптовым ценам для юридических лиц, лучшие цены всегда у нас( но это не точно :D)</h6>

  {% endblock content %}

backend/store/templates/store/ajax_test.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>тестирую fetch</h1>
{% endblock page_header %}

{% block content %}

    <div id="dynamic-content"></div>



    {% block javascript %}
        <script>

        var html = document.getElementById('dynamic-content')

    function buildCards(data){
    let container = document.createElement('div');
    container.className = "container row align-items-stretch row-cols-1 row-cols-sm-2 row-cols-md-4 g-3";

    for(var i = 0; i < data.length; i++){
    let col = document.createElement('div');
    let card = document.createElement('div');
    let img = document.createElement('img');
    let body = document.createElement('p');
    let add_cart = document.createElement('button');
    let description = document.createElement('button');

    col.className = "col d-flex align-items-stretch";
    card.className = "card shadow-sm";
    card.setAttribute("role", "button");
    img.className = "img-fluid m-1";
    body.className = "card-body p-2";
    body.innerHTML = data[i].title;
    add_cart.className = "btn btn-primary m-1";
    add_cart.setAttribute("data-product", data[i].title);
    add_cart.setAttribute("type", "button");
    add_cart.innerHTML = "Добавить в корзину";
    description.className = "btn btn-secondary m-1";
    description.setAttribute("type", "button");
    description.innerHTML = "Подробнее";

    add_cart.addEventListener('click', function(){
      console.log('Вы добавили в корзину товар:', this.dataset.product)
    })


    if ("image" in data[i]){
      img.src = data[i].image;
    }else{
      img.src = "/showcase/default.png";
    }
    card.appendChild(img);
    card.appendChild(body);
    card.appendChild(add_cart);
    card.appendChild(description);
    col.appendChild(card);
    container.appendChild(col);
  }
  html.append(container);
}





        fetch('/fetch_test/')
  .then((response) => {
    return response.json();
  })
  .then((data) => {
     buildCards(data);
  });



    </script>
    {% endblock javascript %}


{% endblock content %}



{% comment %}


{% endcomment %}

backend/store/templates/store/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
 <head>
     	<title>Магазин</title>
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}


 </head>
 <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'store:index' %}">PC Shop</a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'store:categories' %}">{{ menu_items.0 }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:shops' %}">{{ menu_items.1 }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:about' %}">{{ menu_items.2 }}</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}">{{ menu_items.3 }}{% with total_items=cart|length %}
            {% if cart|length > 0 %}
           (Количество: {{ total_items }},
           На сумму ${{ cart.get_total_price }})
            {% else %}
            (Пустая)
            {% endif %}
            {% endwith %}</a>
        </li>
         {% if user.is_authenticated %}
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'orders:profile' %}">{{ menu_items.4 }}</a>
        </li>
        <li class="nav-item">
             <a class="nav-link" href="{% url 'store:logout' %}">Выйти</a>
         </li>
         {% else %}
         <li class="nav-item">
           <a class="nav-link" href="{% url 'store:register' %}">Зарегистрироваться</a>
         </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'store:login' %}">Войти</a>
          </li>
         {% endif %}
      </ul>
    </div>
  </div>
  </nav>

<div class="container">
<div class="row">
   {% block header_parent %}
  <div class="list-group" style="width: 19rem;">
    {% for cat in categories %}
  <a href="{{ cat.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-dark">{{ cat }}</a>
   {% endfor %}
   {% endblock %}

  </div>


    <div class="col-sm-8">
      <div class="d-flex justify-content-center">{% block page_header %}{% endblock page_header %}
      </div>

     <div class="d-flex justify-content-right">
     </div>
      {% block content %}{% endblock content %}


    </div>

  </div>
</div>


 </body>

 <body class="d-flex flex-column min-vh-100">
     <div class="wrapper flex-grow-1"></div>
     <footer class="bg-light text-center text-lg-start" >
     <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      PC Shop© 2021 Все права защищены. {{ menu_items.5 }}
     </div>
    </footer>

 </body>

 </html>

backend/store/templates/store/categories.html
{% extends "store/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block header_parent %}
<!-- Nothing here (to override this portion defined in the parent template) -->
{% endblock %}

{% block page_header %}
  <h1>Выберите категорию</h1>
{% endblock page_header %}



{% block content %}
{% for object in object_list %}

<div class="list-group">
    <a href="{{ object.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-dark"><h1>{{ object }}</h1><br><br><p>{{ object.describe }}</p></a>
</div>
<br>
{% endfor %}


{% endblock content %}

backend/store/templates/store/category.html
{% extends "store/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block page_header %}
  <h1>{{ object }}</h1>
{% endblock page_header %}

{% block content %}

{% for product in object.products.all %}
<div class="card">
  <h5 class="card-header"><small>Добавлен {{ product.created }}</small></h5>
  <div class="card-body">
    <h5 class="card-title text-center">{{ product.name }}</h5>
    {% if product.image %}
    <img class="col-8 img-fluid rounded mx-auto d-block" src="{{ product.image.url }}" alt="Responsive image">
    {% else %}
    <p></p>
    {% endif %}
    <p>Цена {{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Подробнее о товаре</a>
    </div>
</div>
<br>

{% endfor %}


{% endblock content %}

backend/store/templates/store/index.html
{% extends "store/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block page_header %}
  <h1>Последние добавленные товары</h1>
{% endblock page_header %}



{% block content %}

{% for product in products %}
<div class="card">
  <h5 class="card-header"><small>Добавлен {{ product.created }}</small></h5>
  <div class="card-body">
    <h5 class="card-title text-center">{{ product }}</h5>
    <img class="col-8 img-fluid rounded mx-auto d-block" src="{{ product.image.url }}" alt="Responsive image">
    <p class="card-text">Цена {{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Подробнее о товаре</a>
  </div>
</div>
<br>
{% endfor %}





{% endblock content %}

backend/store/templates/store/product.html
{% extends "store/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block page_header %}
  <h1>{{ object }}</h1>

{% endblock page_header %}

{% block content %}
<div class="card">
  <h5 class="card-header"><small>Добавлен {{ object.created }}</small></h5>
  <div class="card-body">
    <h5 class="card-title text-center">{{ object.name }}</h5>
    {% if object.image %}
    <img class="col-8 img-fluid rounded mx-auto d-block" src="{{ product.image.url }}" alt="Responsive image">
    {% else %}
    <p></p>
    {% endif %}
    <p>Цена {{ object.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Добавить в корзину">
    </form>
    <br><br>
    <p>{{ object.description }}</p>
    </div>
</div>
<br><br>
<h2>{% for message in messages %} <div class="p-3 mb-2 bg-warning text-dark"> {{ message }} Пожалуйста, <a href="{% url 'store:register' %}">зарегистрируйтесь</a> или <a href="{% url 'store:login' %}">авторизуйтесь</a> </div> {% endfor %}</h2>

<span class="current">
 Страница {{ comments.number }} из {{ comments.paginator.num_pages }}.
</span>
<ul class="pagination">
   {% if comments.has_previous %}
       <li class="page-item"><a class="page-link" href="?page=1">&laquo; Первая</a></li>
       <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Предыдущая</a></li>
   {% endif %}



   {% if comments.has_next %}
       <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Следующая</a></li>
       <li class="page-item"><a class="page-link" href="?page={{ comments.paginator.num_pages }}">Последняя &raquo;</a></li>
   {% endif %}
</ul>
<div class="container">
     <div class="row py-3">
         <div class="col-3 order-2" id="sticky-sidebar">
           <div class="sticky-top">
             <form id="UserCommentForm" method='post' class="form">
               {% csrf_token %}
               {% bootstrap_form form %}

               {% buttons %}
                 <button name="submit" class="btn btn-primary">Добавить комментарий</button>
               {% endbuttons %}
           </form>
         </div>
       </div>
    <div class="col" id="main">
      <h3>Комментарии:</h3>
       {% for comment in comments %}
       <h6 class="card-header">
       {{ comment.author }}<small> добавлен {{ comment.created_at|date:'M d, Y H:i' }} </small>
       </h6>
        <div class="card-body">
        <h4>{{ comment }}</h4>
        <form id="like-{{comment.pk}}" method="POST" action="{% url 'store:add_like' comment.pk %}">
                    {% csrf_token %}

                    <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                        <a class="btn btn-success" id="like-count-{{comment.pk}}"> Likes {{ comment.likes.all.count }}</a>
                    </button>
                </form>
        <form id="dislike-{{comment.pk}}" method="POST" action="{% url 'store:add_dislike' comment.pk %}">
                    {% csrf_token %}

                    <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                        <a class="btn btn-danger" id="dislike-count-{{comment.pk}}"> Dislikes {{ comment.dislikes.all.count }}</a>
                    </button>
                </form>

        </div>
        {% empty %}
        <p>Для данного товара  ещё нет комментариев.</p>

        {% endfor %}

              </div>
        </div>
    </div>


    {% block javascript %}

    <script type="text/javascript">

    $(document).ready(function(){


       $("#UserCommentForm").submit(function(e){
    	// prevent from normal form behaviour

          	e.preventDefault();
        	// serialize the form data


          	var serializedData = $(this).serialize();
          	$.ajax({
          		type : 'POST',
          		url :  "{% url 'store:ajax_receiver' %}",
                data : serializedData,
          		success : function(response){
                  location.reload();
                  $("#UserCommentForm")[0].reset();

              },
          		error : function(response){
                    alert("Комментарии доступны только для авторизованных пользователей");
          			console.log(response)
          		}
          	});
       });

       $('[id^="like-"]').submit(function(e){

          	e.preventDefault();
            var endpoint = $(this).attr('action');
            var serializedData = $(this).serializeArray();
      $.ajax({
               type: 'POST',
               url: endpoint,
               data: serializedData,
               success: function(response) {
                     $( "#like-count-"+response["id"].toString()).text("Likes "+response["like_count"]);
                     $( "#dislike-count-"+response["id"].toString()).text("Dislikes "+response["dislike_count"]);

                },
                error: function() {
                       alert("Лайки доступны только для авторизованных пользователей");
                }
          });
    })

        $('[id^="dislike-"]').submit(function(e){

          	e.preventDefault();
            var endpoint = $(this).attr('action');
            var serializedData = $(this).serializeArray();
      $.ajax({
               type: 'POST',
               url: endpoint,
               data: serializedData,
               success: function(response) {
                     $( "#like-count-"+response["id"].toString()).text("Likes "+response["like_count"]);
                     $( "#dislike-count-"+response["id"].toString()).text("Dislikes "+response["dislike_count"]);

                },
                error: function() {
                       alert("Дислайки доступны только для авторизованных пользователей");
                }
          });
    })

    });


    </script>

    {% endblock javascript %}


{% endblock content %}

backend/store/templates/store/shops.html
{% extends "store/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h1>Адреса магазинов</h1>
{% endblock page_header %}

{% block content %}
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Название</th>
      <th>Адрес</th>
      <th>Время работы</th>
    </tr>
  </thead>
  <tbody>
    <tr class='success'>
        <td>PC Shop на горе</td>
        <td>улица Мира 657</td>
        <td>с 00:00 до 20:00</td>
    </tr>
      <tr class='success'>
      <td>PC Shop на горбушке</td>
      <td>улица Ленина 8585</td>
      <td>с 08:00 до 18:00</td>
    </tr>
    <tr class='success'>
    <td>PC Shop центральный</td>
    <td>улица Попова 1111</td>
    <td>с 10:00 до 22:00</td>
  </tr>
  </tbody>
  </table>
</div>

    {% endblock content %}