backend/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

backend/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('profile/', views.profile, name='profile'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf', views.admin_order_pdf, name='admin_order_pdf'),
]

backend/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from shop import settings

schema_view = get_schema_view(
    openapi.Info(title="Blog API",
        default_version="v1",
        description="A sample of Shop API for learning DRF",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="hello@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('store.urls')),
    path('api/', include('store.api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import *

app_name = 'store'
urlpatterns = [
	path('', index, name='index'),
	path('categories/', ShowCategories.as_view(), name='categories'),
	path('categories/<slug:category_slug>/', ShowCategory.as_view(), name='category'),
	path('products/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
	path('shops/', show_shops, name='shops'),
	path('about/', about_us, name='about'),
	path('register/', RegisterUser.as_view(), name='register'),
	path('login/', LoginUser.as_view(), name="login"),
	path('logout/', LogoutView.as_view(), name="logout"),
	path('ajax_receiver/', ajax_receiver, name='ajax_receiver'),
	path('products/<int:pk>/like/', addlike, name='add_like'),
	path('products/<int:pk>/dislike/', AddDislike.as_view(), name='add_dislike'),
]

backend/cart/models.py
from django.db import models

# Create your models here.

backend/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label = 'количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

backend/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

backend/cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block page_header %}
  <h1> Корзина ваших товаров</h1>

{% endblock page_header %}


{% block content %}
   <div class="table-responsive">
     <table class="table" id="cart">
      <thead>
        <tr>
            <th>Фото</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за единицу</th>
            <th>Цена</th>
        </tr>
      </thead>
      <tbody>

  {% for item in cart %}
        {% with product=item.product %}
        <tr class='success'>
          <td>
            <a href="{{ product.get_absolute_url }}">
              <img class="col-8 img-fluid rounded mx-auto d-block" src="{% if product.image %}{{ product.image.url }}
              {% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
         </td>
        <td>{{ product.name }}</td>
        <td>
          <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ item.update_quantity_form.quantity }}
          {{ item.update_quantity_form.update }}
          <input type="submit" value="Обновить">
          {% csrf_token %}
          </form>
        </td>
        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
       </tr>
    {% endwith %}
  {% endfor %}
    <tr class="total">
           <td>Всего</td>
           <td colspan="4"></td>
           <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
  </table>
  </div>
  <p class="text-right">
    <a href="{% url 'store:categories' %}" class="btn btn-primary">Продолжить покупки</a>
    <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Оплатить</a>
    </p>
{% endblock content %}